# Generated by Django 5.0.4 on 2024-04-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20)),
            ],
        ),
    ]
